import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1F2937',
  },

  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },

  title: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  subtitle: {
    fontSize: 18,
    color: '#E5E7EB',
    marginBottom: 40,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  form: {
    width: '100%',
    maxWidth: 300,
    marginBottom: 30,
  },

  input: {
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    color: '#E5E7EB',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#4B5563',
    fontFamily: 'Roboto-Regular',
  },

  firebaseStatus: {
    color: '#9CA3AF',
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  screenContainer: {
    flex: 1,
    backgroundColor: '#1F2937',
    alignItems: 'center',
    padding: 20,
    paddingHorizontal: 16,
  },
  difficultyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 20,
  },
  waitingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 20,
  },
  imageHeader: {
    width: '80%',
    maxWidth: 360,
    height: 90,
    marginTop: 80,
    marginBottom: 40,
  },
  header: {
    fontSize: 26,
    fontWeight: '600',
    marginBottom: 20,
    marginTop: 30,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    width: '100%',
  },
  soloheader: {
    fontSize: 26,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: 5,
    marginBottom: 10,
    marginTop: 10,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  button: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 8,
    width: 200,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonText: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  disabledButton: {
    backgroundColor: '#6B7280',
    shadowOpacity: 0,
    elevation: 0,
  },
  guestNotice: {
    backgroundColor: '#374151',
    padding: 16,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
    width: '100%',
    maxWidth: 300,
  },

  guestNoticeText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: 'Roboto-Regular',
  },

  guestNoticeSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  debugInfo: {
    backgroundColor: '#1E3A8A',
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
    width: '100%',
    maxWidth: 300,
    borderWidth: 1,
    borderColor: '#3B82F6',
  },

  debugText: {
    color: '#E5E7EB',
    fontSize: 12,
    fontFamily: 'Roboto-Regular',
    marginBottom: 4,
  },

  benefitsNotice: {
    backgroundColor: '#263238',
    borderRadius: 10,
    padding: 15,
    marginBottom: 30,
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
  },

  benefitsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  benefitItem: {
    fontSize: 14,
    color: '#E5E7EB',
    marginBottom: 5,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  textButton: {
    alignItems: 'center',
    marginTop: 15,
  },

  textButtonText: {
    color: '#F59E0B',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },

  anonymousButton: {
    backgroundColor: '#374151',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 15,
  },

  anonymousButtonText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },

  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 30,
    width: '100%',
    maxWidth: 300,
  },

  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#4B5563',
  },

  dividerText: {
    color: '#9CA3AF',
    marginHorizontal: 15,
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },

  guestNotice: {
    color: '#9CA3AF',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 30,
    fontFamily: 'Roboto-Regular',
  },

  modalText: {
    color: '#E5E7EB',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: 'Roboto-Regular',
    lineHeight: 22,
  },

  modalSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 24,
    fontFamily: 'Roboto-Regular',
    lineHeight: 20,
  },

  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    width: '100%',
  },

  featureList: {
    marginBottom: 30,
    width: '100%',
    maxWidth: 300,
  },

  featureItem: {
    color: '#E5E7EB',
    fontSize: 16,
    marginBottom: 12,
    fontFamily: 'Roboto-Regular',
    textAlign: 'left',
  },
  buttonContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 12,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  savedGameButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 8,
    marginHorizontal: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  savedGameText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  scroll: {
    width: '100%',
    paddingBottom: 50,
  },
  inputDisplay: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  inputLetter: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    textAlign: 'center',
    fontSize: 26,
    marginHorizontal: 6,
    lineHeight: 44,
    borderRadius: 6,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  filledLetter: {
    backgroundColor: '#374151',
  },
  emptyLetter: {
    backgroundColor: '#4B5563',
  },
  alphabetContainer: {
    marginBottom: 10,
    width: '100%',
    alignItems: 'center',
  },
  alphabetGrid: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '100%',
    marginHorizontal: 'auto',
    paddingBottom: 1,
    paddingHorizontal: 1,
  },
  letter: {
    width: 26,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 22,
    margin: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#374151',
    borderRadius: 5,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  eliminatedLetter: {
    backgroundColor: '#6B7280',
    color: '#E5E7EB',
  },
  presentLetter: {
    backgroundColor: '#10B981',
    color: '#1F2937',
  },
  inputControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 20,
  },
  backspaceButtonContainer: {
    backgroundColor: '#7C3AED',
    paddingVertical: 12,
    paddingHorizontal: 26,
    borderRadius: 8,
    marginHorizontal: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  guessButtonContainer: {
    backgroundColor: '#10B981',
    paddingVertical: 12,
    paddingHorizontal: 26,
    borderRadius: 8,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonTextBackspace: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  feedbackGuide: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  feedbackItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
  },
  feedbackCircle: {
    width: 15,
    height: 15,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#7C3AED',
    backgroundColor: 'transparent',
    marginRight: 6,
  },
  feedbackDot: {
    width: 15,
    height: 15,
    borderRadius: 6,
    backgroundColor: '#10B981',
    marginRight: 6,
  },
  feedbackText: {
    fontSize: 14,
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  guessRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
    marginVertical: 2,
  },
  guessWord: {
    flexDirection: 'row',
  },
  guessLetter: {
    fontSize: 26,
    marginHorizontal: 3,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  feedbackContainer: {
    flexDirection: 'row',
  },
  fabTop: {
    position: 'absolute',
    top: 30,
    right: 20,
    backgroundColor: '#F59E0B',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  fabText: {
    color: '#1F2937',
    fontSize: 26,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  modalShadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    marginVertical: 12,
    width: '100%',
    borderRadius: 8,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  invalidGuessTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  congratsPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  congratsTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  congratsMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  congratsButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  winPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  winTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  winMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  winButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  losePopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  loseTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  loseMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  loseButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  opponentGuessesPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  opponentGuessesTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  opponentGuessesMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  opponentGuessesButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  opponentSolvedPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  opponentSolvedTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  opponentSolvedMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  maxGuessesTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  menuPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  menuTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  menuButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  quitConfirmPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  quitConfirmTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  quitConfirmMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  quitConfirmButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  wordRevealPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  wordRevealTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  wordRevealMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  wordRevealButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  hintPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  hintTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  hintMessage: {
    fontSize: 16,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  hintButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  hintLinkContainer: {
    marginTop: 1,
    padding: 1,
  },
  hintLink: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#E5E7EB',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  tutorialText: {
    color: '#D1D5DB',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  friendItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 8,
    width: '100%',
  },
  friendText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
    flex: 1,
    marginRight: 10,
  },
  // New styles for friend system
  searchSection: {
    width: '100%',
    marginBottom: 20,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    width: '100%',
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#4B5563',
    backgroundColor: '#374151',
    padding: 12,
    borderRadius: 8,
    color: '#E5E7EB',
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    marginRight: 8,
  },
  searchButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 10,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    width: '100%',
    textAlign: 'left',
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 4,
    width: '100%',
    overflow: 'hidden',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
    position: 'relative',
  },
  activeTabButton: {
    backgroundColor: '#F59E0B',
  },
  tabButtonText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  activeTabButtonText: {
    color: '#1F2937',
  },
  badge: {
    position: 'absolute',
    top: 4,
    right: 8,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  tabContent: {
    width: '100%',
    paddingHorizontal: 4,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    width: '100%',
    justifyContent: 'space-between',
  },
  friendText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
  },
  friendSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
    marginTop: 2,
  },
  emptyText: {
    color: '#9CA3AF',
    fontSize: 16,
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: 'Roboto-Regular',
    marginTop: 20,
  },
  modalText: {
    color: '#E5E7EB',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Roboto-Regular',
  },
  wordLengthContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 20,
  },
  wordLengthButton: {
    backgroundColor: '#10B981',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    margin: 4,
    minWidth: 80,
    alignItems: 'center',
  },
  wordLengthButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  // Profile Screen Styles
  profileHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  backButton: {
    padding: 10,
  },
  backButtonText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
  },
  editButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  editButtonText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '600',
  },
  avatarSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
  },
  avatarContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
    borderWidth: 3,
    borderColor: '#F59E0B',
  },
  avatarIcon: {
    fontSize: 35,
  },
  avatarHint: {
    position: 'absolute',
    bottom: -20,
    fontSize: 9,
    color: '#9CA3AF',
    textAlign: 'center',
    width: 70,
  },
  profileInfo: {
    flex: 1,
  },
  displayName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#E5E7EB',
    marginBottom: 5,
  },
  username: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 8,
  },
  bio: {
    fontSize: 13,
    color: '#D1D5DB',
    lineHeight: 18,
  },
  editForm: {
    width: '100%',
    marginBottom: 20,
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
  },
  inputGroup: {
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#4B5563',
    borderRadius: 8,
    padding: 10,
    color: '#E5E7EB',
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#6B7280',
  },
  textArea: {
    height: 70,
    textAlignVertical: 'top',
  },
  gameStyleOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gameStyleOption: {
    width: '48%',
    backgroundColor: '#4B5563',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  gameStyleOptionSelected: {
    borderColor: '#F59E0B',
    backgroundColor: '#5B6B7A',
  },
  gameStyleLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  gameStyleLabelSelected: {
    color: '#F59E0B',
  },
  gameStyleDescription: {
    fontSize: 11,
    color: '#9CA3AF',
    lineHeight: 14,
  },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  cancelButton: {
    backgroundColor: '#6B7280',
    width: '48%',
  },
  saveButton: {
    backgroundColor: '#10B981',
    width: '48%',
  },
  statsContainer: {
    width: '100%',
    marginBottom: 20,
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  statItem: {
    width: '48%',
    alignItems: 'center',
    marginBottom: 15,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  preferencesSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
  },
  preferenceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
  },
  preferenceLabel: {
    fontSize: 15,
    color: '#E5E7EB',
  },
  preferenceValue: {
    fontSize: 15,
    color: '#F59E0B',
    fontWeight: '600',
  },
  avatarModal: {
    backgroundColor: '#1F2937',
    margin: 20,
    borderRadius: 12,
    padding: 15,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    textAlign: 'center',
    marginBottom: 15,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  avatarOption: {
    width: '30%',
    alignItems: 'center',
    padding: 12,
    marginBottom: 12,
    backgroundColor: '#374151',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  avatarOptionSelected: {
    borderColor: '#F59E0B',
    backgroundColor: '#5B6B7A',
  },
  avatarOptionIcon: {
    fontSize: 25,
    marginBottom: 6,
  },
  avatarOptionName: {
    fontSize: 11,
    color: '#E5E7EB',
    textAlign: 'center',
  },
  // Welcome Section Styles
  welcomeSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  welcomeTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 8,
    textAlign: 'center',
  },
  welcomeText: {
    fontSize: 14,
    color: '#D1D5DB',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 15,
  },
  createProfileButton: {
    backgroundColor: '#10B981',
    width: 'auto',
    paddingHorizontal: 25,
    paddingVertical: 10,
  },
  // Error Section Styles
  errorSection: {
    width: '100%',
    backgroundColor: '#DC2626',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  errorText: {
    fontSize: 14,
    color: '#FECACA',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 15,
  },
  retryButton: {
    backgroundColor: '#FFFFFF',
    width: 'auto',
    paddingHorizontal: 25,
    paddingVertical: 10,
  },
  // Loading Section Styles
  loadingSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  // SetWordGameScreen styles
  gameScrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
    paddingBottom: 40,
  },
  wordContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 20,
    gap: 8,
  },
  letterBox: {
    width: 50,
    height: 50,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1F2937',
  },
  letterText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
  },
  // Alphabet grid letter text styling
  alphabetLetterText: {
    fontSize: 22,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  // Leaderboard styles
  leaderboardItem: {
    flexDirection: 'row',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  currentUserItem: {
    backgroundColor: '#1F2937',
    borderColor: '#F59E0B',
    borderWidth: 2,
  },
  rankContainer: {
    width: 60,
    alignItems: 'center',
  },
  rankText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
  },
  topRankText: {
    color: '#F59E0B',
  },
  medal: {
    fontSize: 16,
    marginTop: 2,
  },
  playerInfo: {
    flex: 1,
    marginLeft: 15,
  },
  playerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 4,
  },
  currentUserName: {
    color: '#F59E0B',
  },
  playerStats: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  scoreContainer: {
    alignItems: 'center',
    minWidth: 80,
  },
  scoreText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 2,
  },
  topScoreText: {
    color: '#F59E0B',
  },
  scoreLabel: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  gamesCountText: {
    fontSize: 10,
    color: '#6B7280',
    fontFamily: 'Roboto-Regular',
    marginTop: 2,
  },
  userRankContainer: {
    backgroundColor: '#1F2937',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  userRankTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  tipsContainer: {
    backgroundColor: '#1F2937',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  tipsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  tipText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginBottom: 8,
    lineHeight: 20,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  actionButton: {
    backgroundColor: '#6B7280',
    width: 80,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  // Additional SetWordGameScreen styles
  alphabetContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 30,
    paddingHorizontal: 10,
    maxWidth: '100%',
  },
  letterButton: {
    width: 35,
    height: 35,
    backgroundColor: '#374151',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
    margin: 1,
  },
  letterButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
  },
  subtitle: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
    lineHeight: 22,
    fontFamily: 'Roboto-Regular',
  },
  // Difficulty selection container
  difficultyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 20,
  },
  // FriendsScreen navigation styles
  navigationContainer: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
    gap: 15,
  },
  navCard: {
    backgroundColor: '#374151',
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4B5563',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  navCardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 8,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  navCardSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    lineHeight: 20,
  },
  createChallengeCard: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
  },
  // Group styling for FriendsScreen
  groupContainer: {
    width: '100%',
    marginBottom: 20,
  },
  groupTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 15,
    fontFamily: 'Roboto-Medium',
    textAlign: 'left',
  },
  // Tab styling for Friends Management
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
    marginHorizontal: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
  },
  activeTabButton: {
    backgroundColor: '#F59E0B',
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    fontFamily: 'Roboto-Medium',
  },
  activeTabButtonText: {
    color: '#1F2937',
  },
  // Missing styles for FriendsScreen and AddFriendsScreen
  searchSection: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
    backgroundColor: '#374151',
    marginBottom: 10,
    borderRadius: 12,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 10,
    width: '100%',
  },
  searchInput: {
    flex: 1,
    minWidth: 200,
    backgroundColor: '#1F2937',
    borderRadius: 8,
    padding: 12,
    color: '#E5E7EB',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#4B5563',
    fontFamily: 'Roboto-Regular',
  },
  searchButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchButtonText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
  },
  searchResults: {
    marginTop: 15,
  },
  resultsTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 15,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Medium',
    textAlign: 'center',
  },
  userItem: {
    backgroundColor: '#1F2937',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  userInfo: {
    marginBottom: 10,
  },
  username: {
    fontSize: 18,
    fontWeight: '600',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 5,
  },
  userEmail: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  addButton: {
    backgroundColor: '#3B82F6',
  },
  requestItem: {
    backgroundColor: '#1F2937',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  requestInfo: {
    marginBottom: 10,
  },
  requestUsername: {
    fontSize: 18,
    fontWeight: '600',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 5,
  },
  requestText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  requestActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  acceptButton: {
    backgroundColor: '#10B981',
  },
  declineButton: {
    backgroundColor: '#6B7280',
  },
  requestsContainer: {
    flex: 1,
    width: '100%',
  },
  emptyContainer: {
    alignItems: 'center',
    padding: 20,
    marginTop: 20,
  },
  emptyText: {
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 16,
    fontStyle: 'italic',
    marginTop: 20,
    fontFamily: 'Roboto-Regular',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#6B7280',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    marginTop: 5,
  },
  // Challenge text styling for better readability
  challengeUsername: {
    fontSize: 16,
    fontWeight: '600',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 3,
  },
  challengeEmail: {
    fontSize: 14,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    marginBottom: 3,
  },
  challengeDifficulty: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    fontStyle: 'italic',
    marginTop: 3,
  },
  // Challenge item container styling
  challengeItem: {
    backgroundColor: '#1F2937',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  challengeInfo: {
    marginBottom: 10,
  },
  challengeActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
});