import { StyleSheet, Dimensions, Platform } from 'react-native';
import { isTablet, responsiveWidth, responsiveFontSize, responsiveSpacing, getContentWidth } from './responsive';

// Helper to get responsive values
const rw = responsiveWidth;
const rf = responsiveFontSize;
const rs = responsiveSpacing;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1F2937',
  },

  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: rs(20, 30),
  },

  title: {
    fontSize: rf(48, 64),
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: rs(10, 15),
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  subtitle: {
    fontSize: rf(18, 22),
    color: '#E5E7EB',
    marginBottom: rs(40, 50),
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  form: {
    width: '100%',
    maxWidth: rw(300, 500),
    marginBottom: rs(30, 40),
  },

  input: {
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    color: '#E5E7EB',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#4B5563',
    fontFamily: 'Roboto-Regular',
  },
  readOnlyField: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: '#4B5563',
    borderRadius: 8,
    paddingHorizontal: 16,
    backgroundColor: '#1F2937',
    justifyContent: 'center',
    marginBottom: 16,
  },
  readOnlyLabel: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginBottom: 2,
  },
  readOnlyValue: {
    fontSize: 16,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },

  firebaseStatus: {
    color: '#9CA3AF',
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  screenContainer: {
    flex: 1,
    backgroundColor: '#1F2937',
    paddingHorizontal: 16,
  },
  difficultyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 20,
  },
  waitingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 20,
  },
  imageHeader: {
    width: '80%',
    maxWidth: rw(360, 550),
    height: rf(90, 120),
    marginTop: rs(80, 100),
    marginBottom: rs(40, 60),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    fontSize: 26,
    fontWeight: '600',
    marginBottom: 20,
    marginTop: 30,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    width: '100%',
  },
  soloheader: {
    fontSize: 26,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: 5,
    marginBottom: 15,
    marginTop: 25, // Increased top margin to avoid FAB overlap
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  button: {
    backgroundColor: '#F59E0B',
    paddingVertical: rs(12, 16),
    paddingHorizontal: rs(24, 32),
    borderRadius: rs(8, 10),
    marginVertical: rs(8, 12),
    width: '90%',
    maxWidth: rw(320, 500),
    minWidth: rw(280, 400),
    alignItems: 'center',
    alignSelf: 'center',
    // 3D bevel + stronger shadow
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  buttonText: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    numberOfLines: 1,
    ellipsizeMode: 'clip',
  },

  difficultyButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: rs(12, 18),
    paddingHorizontal: rs(20, 32),
    borderRadius: rs(8, 12),
    marginVertical: rs(8, 12),
    width: '95%',
    maxWidth: rw(350, 550),
    minWidth: rw(300, 450),
    alignItems: 'center',
    alignSelf: 'center',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },

  guestNotice: {
    backgroundColor: '#374151',
    padding: 16,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
    width: '100%',
    maxWidth: 300,
  },

  guestNoticeText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: 'Roboto-Regular',
  },

  guestNoticeSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  debugInfo: {
    backgroundColor: '#1E3A8A',
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
    width: '100%',
    maxWidth: 300,
    borderWidth: 1,
    borderColor: '#3B82F6',
  },



  benefitsNotice: {
    backgroundColor: '#263238',
    borderRadius: 10,
    padding: 15,
    marginBottom: 30,
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
  },

  benefitsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  benefitItem: {
    fontSize: 14,
    color: '#E5E7EB',
    marginBottom: 5,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  textButton: {
    alignItems: 'center',
    marginTop: 15,
  },

  textButtonText: {
    color: '#F59E0B',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },

  anonymousButton: {
    backgroundColor: '#374151',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 15,
  },

  anonymousButtonText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },

  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 30,
    width: '100%',
    maxWidth: 300,
  },

  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#4B5563',
  },

  dividerText: {
    color: '#9CA3AF',
    marginHorizontal: 15,
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },

  guestNotice: {
    color: '#9CA3AF',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 30,
    fontFamily: 'Roboto-Regular',
  },

  modalText: {
    color: '#E5E7EB',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: 'Roboto-Regular',
    lineHeight: 22,
  },

  modalSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 24,
    fontFamily: 'Roboto-Regular',
    lineHeight: 20,
  },

  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    width: '100%',
  },

  featureList: {
    marginBottom: 30,
    width: '100%',
    maxWidth: 300,
  },

  featureItem: {
    color: '#E5E7EB',
    fontSize: 16,
    marginBottom: 12,
    fontFamily: 'Roboto-Regular',
    textAlign: 'left',
  },
  buttonContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 2,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    alignSelf: 'center',
    width: '100%',
  },
  
  sectionSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 16,
    fontFamily: 'Roboto-Regular',
    lineHeight: 20,
  },

  scroll: {
    width: '100%',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  inputDisplay: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    width: '100%',
  },
  inputLetter: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    textAlign: 'center',
    fontSize: 26,
    marginHorizontal: 6,
    lineHeight: 44,
    borderRadius: 6,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filledLetter: {
    backgroundColor: '#374151',
  },
  emptyLetter: {
    backgroundColor: '#4B5563',
  },
  alphabetContainer: {
    marginBottom: -10,
    width: '100%',
    alignItems: 'center',
  },
  alphabetGrid: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '100%',
    alignSelf: 'center',
    paddingBottom: 1,
    paddingHorizontal: 10, // Add horizontal padding to prevent edge overflow
  },
  letter: {
    // Dynamic sizing based on screen width
    minWidth: 24,
    minHeight: 32,
    maxWidth: 32,
    maxHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 18, // Reduced base font size
    margin: 2, // Reduced margin for better fit
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#374151',
    borderRadius: 5,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    // Use flex to make letters responsive
    flex: 1,
    aspectRatio: 1, // Keep letters square
  },

  eliminatedLetter: {
    backgroundColor: '#6B7280',
  },
  presentLetter: {
    backgroundColor: '#10B981',
  },
  inputControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 15,
    marginTop: -30,
  },
  // Style for PvP word setting screen (no negative margin)
  inputControlsPvP: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 15,
    marginTop: 20,
  },
  backspaceButtonContainer: {
    backgroundColor: '#7C3AED',
    paddingVertical: 12,
    paddingHorizontal: 26,
    borderRadius: 8,
    marginHorizontal: 6,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#8B5CF6',
    borderLeftColor: '#8B5CF6',
    borderBottomColor: '#5B21B6',
    borderRightColor: '#5B21B6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    minWidth: 140,
  },
  guessButtonContainer: {
    backgroundColor: '#10B981',
    paddingVertical: 12,
    paddingHorizontal: 26,
    borderRadius: 8,
    marginHorizontal: 20,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#34D399',
    borderLeftColor: '#34D399',
    borderBottomColor: '#059669',
    borderRightColor: '#059669',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    minWidth: 140,
  },
  buttonTextBackspace: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    numberOfLines: 1,
    ellipsizeMode: 'clip',
  },
  feedbackGuide: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 5,
  },
  feedbackItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
  },
  feedbackCircle: {
    width: 15,
    height: 15,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#7C3AED',
    backgroundColor: 'transparent',
    marginRight: 6,
  },
  feedbackDot: {
    width: 15,
    height: 15,
    borderRadius: 6,
    backgroundColor: '#10B981',
    marginRight: 6,
  },
  feedbackText: {
    fontSize: 14,
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  guessGrid: {
    marginHorizontal: 20,
    marginVertical: 2,
  },
  guessRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 0,
    paddingVertical: 0,
  },
  guessWord: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
    width: 120, // Reduced width for tighter letter spacing
  },
  guessLetter: {
    fontSize: 26,
    marginHorizontal: 0,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    width: 24, // Reduced width for tighter letter spacing
    height: 40,
    lineHeight: 40,
    flex: 1, // This ensures each letter takes equal space
  },
  feedbackContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
  },
  fabTop: {
    position: 'absolute',
    top: 10, // Reduced top margin since SafeAreaView already handles status bar spacing
    right: 20,
    backgroundColor: '#F59E0B',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 1000,
    // Ensure consistent positioning across all screens
    left: undefined,
    bottom: undefined,
  },
  
  // Alternative FAB positioning for screens with heavy top margins
  fabTopFixed: {
    position: 'absolute',
    // top value is now set dynamically using safe area insets
    right: 20,
    backgroundColor: '#F59E0B',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 1000,
  },
  // HomeScreen specific FAB positioning
  fabTopHomeScreen: {
    position: 'absolute',
    top: 5, // Top right corner with minimal safe area spacing
    right: 20,
    backgroundColor: '#F59E0B',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 1000,
  },
  fabText: {
    color: '#1F2937',
    fontSize: 26,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  modalContainer: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  modalShadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  videoModal: {
    backgroundColor: '#1F2937',
    borderRadius: 10,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
    zIndex: 10000,
  },
  videoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  videoTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    flex: 1,
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  videoPlayer: {
    width: '100%',
    height: 300,
    borderRadius: 8,
  },
  videoButton: {
    backgroundColor: '#8B5CF6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 15,
    alignItems: 'center',
  },
  videoButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  videoModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  video: {
    width: '100%',
    height: 300,
    borderRadius: 8,
  },
  videoCloseButton: {
    position: 'absolute',
    top: 10,
    right: 15,
    zIndex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoCloseButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    marginVertical: 12,
    width: '100%',
    borderRadius: 8,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  invalidGuessTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  congratsPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  congratsTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  congratsMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  congratsButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  winPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  winTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  winMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  waitingMessage: {
    fontSize: 14,
    marginBottom: 12,
    textAlign: 'center',
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    fontStyle: 'italic',
  },
  winButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  losePopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  loseTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  loseMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  loseButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  opponentGuessesPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  opponentGuessesTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  opponentGuessesMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  opponentGuessesButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  opponentSolvedPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  opponentSolvedTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  opponentSolvedMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  maxGuessesTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  tiePopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  tieTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  tieMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  tieButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  menuPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  menuTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  menuButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    width: '100%',
    alignItems: 'center',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  quitConfirmPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  quitConfirmTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  quitConfirmMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  quitConfirmButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  wordRevealPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  wordRevealTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  wordRevealMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  wordRevealButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  hintPopup: {
    backgroundColor: '#374151',
    padding: rs(24, 32),
    borderRadius: rs(12, 16),
    alignItems: 'center',
    width: isTablet() ? '60%' : '85%',
    maxWidth: rw(500, 700),
  },
  hintTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  hintMessage: {
    fontSize: 16,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  hintButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 8,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  hintLinkContainer: {
    marginTop: 1,
    padding: 1,
  },
  hintLink: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  
  // Rank-up popup styles
  rankUpPopup: {
    backgroundColor: '#1F2937',
    padding: rs(32, 40),
    borderRadius: rs(16, 20),
    alignItems: 'center',
    width: isTablet() ? '65%' : '90%',
    maxWidth: rw(550, 750),
    borderWidth: 3,
    borderColor: '#F59E0B',
  },
  rankUpTitle: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 8,
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  rankUpSubtitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  rankUpMessage: {
    fontSize: 16,
    marginBottom: 24,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
    lineHeight: 24,
  },
  rankUpButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  rankUpButtonText: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Roboto-Bold',
  },
  
  // Rank display styles for HomeScreen
  rankDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F59E0B',
  },
  // Notifications indicator styles for HomeScreen
  notificationsIndicator: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#1D4ED8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  notificationsText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  rankLabel: {
    color: '#D1D5DB',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
    marginRight: 8,
  },
  rankValue: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Roboto-Bold',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#E5E7EB',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  tutorialText: {
    color: '#D1D5DB',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  friendItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 8,
    width: '100%',
  },
  friendText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
    flex: 1,
    marginRight: 10,
  },
  // New styles for friend system
  searchSection: {
    width: '100%',
    marginBottom: 20,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    width: '100%',
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#4B5563',
    backgroundColor: '#374151',
    padding: 12,
    borderRadius: 8,
    color: '#E5E7EB',
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    marginRight: 8,
  },
  searchButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 10,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    width: '100%',
    textAlign: 'left',
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
    justifyContent: 'space-between',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    minWidth: 0,
    maxWidth: '25%',
  },
  activeTabButton: {
    backgroundColor: '#F59E0B',
  },
  tabButtonText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    flexShrink: 1,
  },
  tabLink: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    minWidth: 0,
  },
  tabLinkText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    flexShrink: 1,
  },
  activeTabButtonText: {
    color: '#1F2937',
  },
  badge: {
    position: 'absolute',
    top: 4,
    right: 8,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  tabContent: {
    width: '100%',
    paddingHorizontal: 4,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    width: '100%',
    justifyContent: 'space-between',
  },
  friendText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
  },
  friendSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
    marginTop: 2,
  },
  emptyText: {
    color: '#9CA3AF',
    fontSize: 16,
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: 'Roboto-Regular',
    marginTop: 20,
  },
  modalText: {
    color: '#E5E7EB',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Roboto-Regular',
  },
  wordLengthContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 20,
  },
  wordLengthButton: {
    backgroundColor: '#10B981',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    margin: 4,
    minWidth: 80,
    alignItems: 'center',
  },
  wordLengthButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  // Profile Screen Styles
  profileHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  backButton: {
    padding: 10,
  },
  backButtonText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
  },
  // Resume screen styles
  resumeBackButton: {
    padding: 10,
  },
  resumeBackButtonText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
    flex: 1,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  emptyStateSubtitle: {
    fontSize: 16,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    marginBottom: 25,
    lineHeight: 22,
  },
  addFriendsButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#FBBF24',
    borderLeftColor: '#FBBF24',
    borderBottomColor: '#B45309',
    borderRightColor: '#B45309',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  addFriendsButtonText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
    backgroundColor: '#1F2937',
    minHeight: 60, // Ensure minimum height
    zIndex: 1, // Ensure header stays on top
  },
  emptyStateContainer: {
    alignItems: 'center',
    padding: 30,
    justifyContent: 'center',
    flex: 1,
  },
  sectionContainer: {
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  editButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  editButtonText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '600',
  },
  // Rank Display Styles
  rankDisplayContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 15,
  },
  rankBadge: {
    flex: 1,
    backgroundColor: '#374151',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  rankTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  rankSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  // Profile Section Styles
  profileSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  // Profile Info Styles
  profileInfo: {
    width: '100%',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
  },
  infoLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Medium',
  },
  infoValue: {
    fontSize: 16,
    color: '#F59E0B',
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
    textAlign: 'right',
    flex: 1,
    marginLeft: 10,
  },
  // Settings Section Styles
  settingsBackButton: {
    padding: 10,
  },
  settingsBackButtonText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
  },
  settingsSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
    alignSelf: 'stretch',
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
    flexWrap: 'wrap',
  },
  settingLabel: {
    fontSize: 16,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Medium',
  },
  settingValue: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  frequencyButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    minWidth: 80,
    alignItems: 'center',
  },
  frequencyButtonText: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Roboto-Medium',
  },
  // Actions Section Styles
  actionsSection: {
    width: '100%',
    marginBottom: 30,
    gap: 15,
    alignItems: 'center',
  },
  signOutButton: {
    backgroundColor: '#EF4444',
    borderColor: '#DC2626',
  },
  deleteButton: {
    backgroundColor: '#DC2626',
    borderColor: '#B91C1C',
  },
  // Stats Styles
  statNumber: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 4,
    fontFamily: 'Roboto-Bold',
  },
  // Modal Actions Styles
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 15,
    marginTop: 20,
  },
  modalActionsVertical: {
    flexDirection: 'column',
    gap: 15,
    marginTop: 20,
    width: '100%',
  },
  avatarSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
  },
  avatarContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
    borderWidth: 3,
    borderColor: '#F59E0B',
  },
  avatarIcon: {
    fontSize: 35,
  },
  avatarHint: {
    position: 'absolute',
    bottom: -20,
    fontSize: 9,
    color: '#9CA3AF',
    textAlign: 'center',
    width: 70,
  },
  
  // Theme Selector Styles
  themeSelector: {
    flexDirection: 'row',
    gap: 8,
  },
  
  themeOption: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  
  themeOptionText: {
    fontSize: 14,
    fontWeight: '600',
  },
  
  // Volume Slider Styles
  volumeSlider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  
  volumeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  volumeButtonText: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: 'bold',
  },
  
  volumeText: {
    fontSize: 14,
    minWidth: 40,
    textAlign: 'center',
  },
  
  // Action Button Styles
  actionButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },

  // Enhanced Action Button Styles
  enhancedActionButton: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 56,
    justifyContent: 'center',
  },

  enhancedActionButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.5,
  },

  // Cache Management Styles
  cacheManagementContainer: {
    marginBottom: 20,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },

  cacheInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 4,
  },

  cacheInfoLabel: {
    fontSize: 14,
    fontWeight: '500',
  },

  cacheInfoValue: {
    fontSize: 16,
    fontWeight: '700',
  },

  cacheDescription: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  
  // Time Button Styles
  timeButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  
  timeButtonText: {
    fontSize: 14,
    fontWeight: '500',
  },
  
  // Modal Styles for Settings
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 16,
    textAlign: 'center',
  },
  
  timeInput: {
    borderWidth: 1,
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
    width: '100%',
  },
  
  // Privacy Settings Styles
  privacyLevelButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  
  privacyLevelText: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 4,
  },
  
  privacyLevelSubtext: {
    fontSize: 14,
    opacity: 0.8,
  },
  
  privacySelector: {
    flexDirection: 'row',
    gap: 6,
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    width: '100%',
    marginTop: 8,
    alignSelf: 'stretch',
  },
  
  privacyOption: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 60,
    maxWidth: '100%',
    alignItems: 'center',
    flexShrink: 1,
    flex: 1,
  },
  
  privacyOptionText: {
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
    flexWrap: 'wrap',
    flexShrink: 1,
  },

  // Special style for setting items with privacy selectors
  settingItemWithSelector: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
  },
  
  infoContainer: {
    padding: 14,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 8,
  },
  
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  
  infoText: {
    fontSize: 14,
    lineHeight: 20,
  },
  
  // Friend Discovery Styles
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
  },
  
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  
  tabButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  
  searchContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  
  searchInput: {
    flex: 1,
    borderWidth: 1,
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
  },
  
  searchButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 80,
  },
  
  searchButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  
  resultsContainer: {
    marginTop: 16,
  },
  
  resultsTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  
  userCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 8,
    marginBottom: 8,
  },
  
  userInfo: {
    flex: 1,
  },
  
  username: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 4,
  },
  
  userStats: {
    fontSize: 14,
    marginBottom: 4,
  },
  
  friendOfFriend: {
    fontSize: 12,
    fontWeight: '500',
  },
  
  addFriendButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  
  addFriendButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  
  emptyState: {
    alignItems: 'center',
    padding: 32,
  },
  
  emptyStateText: {
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
    color: '#FFFFFF',
  },
  
  leaderboardInfo: {
    padding: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 8,
    marginBottom: 16,
  },
  editForm: {
    width: '100%',
    marginBottom: 20,
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
  },
  inputGroup: {
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#4B5563',
    borderRadius: 8,
    padding: 10,
    color: '#E5E7EB',
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#6B7280',
  },
  textArea: {
    height: 70,
    textAlignVertical: 'top',
  },
  gameStyleOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gameStyleOption: {
    width: '48%',
    backgroundColor: '#4B5563',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  gameStyleOptionSelected: {
    borderColor: '#F59E0B',
    backgroundColor: '#5B6B7A',
  },
  gameStyleLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  gameStyleLabelSelected: {
    color: '#F59E0B',
  },
  gameStyleDescription: {
    fontSize: 11,
    color: '#9CA3AF',
    lineHeight: 14,
  },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  cancelButton: {
    backgroundColor: '#6B7280',
    width: '48%',
  },
  saveButton: {
    backgroundColor: '#10B981',
    width: '48%',
  },
  statsContainer: {
    width: '100%',
    marginBottom: 20,
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  statItem: {
    width: '48%',
    alignItems: 'center',
    marginBottom: 15,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 4,
  },
  statNumber: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 4,
    fontFamily: 'Roboto-Bold',
  },
  statLabel: {
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  preferencesSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
  },
  preferenceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
  },
  preferenceLabel: {
    fontSize: 15,
    color: '#E5E7EB',
  },
  preferenceValue: {
    fontSize: 15,
    color: '#F59E0B',
    fontWeight: '600',
  },
  avatarModal: {
    backgroundColor: '#1F2937',
    margin: 20,
    borderRadius: 12,
    padding: 15,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    textAlign: 'center',
    marginBottom: 15,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  avatarOption: {
    width: '30%',
    alignItems: 'center',
    padding: 12,
    marginBottom: 12,
    backgroundColor: '#374151',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  avatarOptionSelected: {
    borderColor: '#F59E0B',
    backgroundColor: '#5B6B7A',
  },
  avatarOptionIcon: {
    fontSize: 25,
    marginBottom: 6,
  },
  avatarOptionName: {
    fontSize: 11,
    color: '#E5E7EB',
    textAlign: 'center',
  },
  // Welcome Section Styles
  welcomeSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  welcomeTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 8,
    textAlign: 'center',
  },
  welcomeText: {
    fontSize: 14,
    color: '#D1D5DB',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 15,
  },
  createProfileButton: {
    backgroundColor: '#10B981',
    width: 'auto',
    paddingHorizontal: 25,
    paddingVertical: 10,
  },
  // Error Section Styles
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorSection: {
    width: '100%',
    backgroundColor: '#DC2626',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  errorText: {
    fontSize: 14,
    color: '#FECACA',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 15,
  },
  errorMessage: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#FFFFFF',
    width: 'auto',
    paddingHorizontal: 25,
    paddingVertical: 10,
  },
  // Loading Section Styles
  loadingSection: {
    width: '100%',
    backgroundColor: '#374151',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  // SetWordGameScreen styles
  gameScrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
    paddingBottom: 40,
  },
  wordContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 20,
    gap: 8,
  },
  letterBox: {
    width: '12%',
    maxWidth: 60,
    minWidth: 45,
    aspectRatio: 1,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1F2937',
  },
  letterText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
  },
  // Alphabet grid letter text styling
  alphabetLetterText: {
    fontSize: 22,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  // Notification styles
  notificationsContainer: {
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  notificationItem: {
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  notificationText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    flex: 1,
    marginRight: 10,
  },
  dismissNotificationButton: {
    backgroundColor: '#6B7280',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dismissNotificationButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  stuckGameContainer: {
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
    alignItems: 'center',
  },
  stuckGameText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontFamily: 'Roboto-Bold',
    marginBottom: 8,
  },
  stuckGameSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
    marginBottom: 15,
    textAlign: 'center',
  },
  removeStuckGameButton: {
    backgroundColor: '#DC2626',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 6,
  },
  removeStuckGameButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Roboto-Bold',
  },


  // Leaderboard styles
  leaderboardItem: {
    flexDirection: 'row',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  currentUserItem: {
    backgroundColor: '#1F2937',
    borderColor: '#F59E0B',
    borderWidth: 2,
  },
  rankContainer: {
    width: 60,
    alignItems: 'center',
  },
  rankText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
  },
  topRankText: {
    color: '#F59E0B',
  },
  medal: {
    fontSize: 16,
    marginTop: 2,
  },
  playerInfo: {
    flex: 1,
    marginLeft: 15,
  },
  playerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 4,
  },
  currentUserName: {
    color: '#F59E0B',
  },
  playerStats: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  scoreContainer: {
    alignItems: 'center',
    minWidth: 80,
  },
  scoreText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 2,
  },
  topScoreText: {
    color: '#F59E0B',
  },
  scoreLabel: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  scoreHighlight: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
  },
  difficultyScoreText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginTop: 4,
  },
  gamesCountText: {
    fontSize: 10,
    color: '#6B7280',
    fontFamily: 'Roboto-Regular',
    marginTop: 2,
  },
  userRankContainer: {
    backgroundColor: '#1F2937',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  userRankTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  
  // Leaderboard Summary Box styles
  leaderboardSummaryBox: {
    backgroundColor: '#374151',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
    width: '100%',
  },
  summaryBoxHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  summaryBoxTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
  },
  seeMoreButton: {
    backgroundColor: '#F59E0B',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  seeMoreButtonText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
  },
  summaryContent: {
    alignItems: 'center',
  },
  summaryRank: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 8,
  },
  summaryStats: {
    fontSize: 16,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    marginBottom: 12,
    textAlign: 'center',
  },
  difficultyBreakdown: {
    width: '100%',
  },
  difficultyStat: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginBottom: 4,
    textAlign: 'center',
  },
  noDataText: {
    fontSize: 16,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  
  // Expanded Leaderboard styles
  expandedSection: {
    width: '100%',
  },
  expandedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  expandedTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
  },
  backButton: {
    padding: 10,
  },
  backButtonText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  tipsContainer: {
    backgroundColor: '#1F2937',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  tipsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  tipText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginBottom: 8,
    lineHeight: 20,
  },
  // CreateChallengeScreen styles
  friendItem: {
    flexDirection: 'column',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 12, // Increased spacing between items
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  friendInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  friendUsername: {
    fontSize: 18, // Increased font size
    fontWeight: '600',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 4,
    flex: 1, // Allow username to take available space
  },
  friendRecord: {
    fontSize: 14,
    fontWeight: '400',
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginTop: 2,
  },
  removeButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#DC2626',
    backgroundColor: '#DC2626',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  removeButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  // friendEmail style removed since we no longer display emails
  challengeButton: {
    backgroundColor: '#10B981',
    paddingVertical: 12, // Increased padding for better touch target
    paddingHorizontal: 24, // Increased horizontal padding
    borderRadius: 8, // Increased border radius
    marginLeft: 0, // Remove left margin since we're centering
    minWidth: 70, // Ensure minimum width for text
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  checkButton: {
    backgroundColor: '#10B981', // Green for check
  },
  quitButton: {
    backgroundColor: '#EF4444', // Red for quit
  },
  challengeButtonText: {
    color: '#FFFFFF',
    fontSize: 15, // Increased font size
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
    flexShrink: 0,
    flexWrap: 'nowrap',
    numberOfLines: 1,
    ellipsizeMode: 'clip',
  },
  lastFriendItem: {
    marginBottom: 0, // Remove bottom margin for last item
  },
  friendsList: {
    width: '100%',
    marginTop: 10,
  },
  emptyContainer: {
    alignItems: 'center',
    padding: 30,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    marginBottom: 25,
    lineHeight: 22,
  },
  subtitle: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
    lineHeight: 22,
    fontFamily: 'Roboto-Regular',
  },
  friendsContainer: {
    width: '100%',
    marginTop: 10,
    paddingBottom: 20, // Add bottom padding for better scrolling
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  actionButton: {
    backgroundColor: '#6B7280',
    width: 80,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  // Additional SetWordGameScreen styles
  alphabetContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 30,
    paddingHorizontal: 10,
    maxWidth: '100%',
  },
  letterButton: {
    width: 35,
    height: 35,
    backgroundColor: '#374151',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
    margin: 1,
  },
  letterButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
  },
  subtitle: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
    lineHeight: 22,
    fontFamily: 'Roboto-Regular',
  },
  // Difficulty selection container
  difficultyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 20,
  },
  // FriendsScreen navigation styles
  navigationContainer: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
    gap: 15,
  },
  
  // CreateChallengeScreen pending challenges styles
  sectionContainer: {
    width: '100%',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 8,
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 16,
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  challengeItem: {
    backgroundColor: '#374151',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  lastChallengeItem: {
    marginBottom: 0,
  },
  challengeInfo: {
    marginBottom: 12,
  },
  challengerUsername: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
    fontFamily: 'Roboto-Regular',
  },
  challengeDetails: {
    fontSize: 14,
    color: '#D1D5DB',
    marginBottom: 4,
    fontFamily: 'Roboto-Regular',
  },
  challengeTime: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  challengeActions: {
    flexDirection: 'row',
    gap: 12,
  },
  acceptButton: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
  },
  declineButton: {
    backgroundColor: '#EF4444',
    borderColor: '#DC2626',
  },
  acceptButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  declineButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  navCard: {
    backgroundColor: '#374151',
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4B5563',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  navCardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 8,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  navCardSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    lineHeight: 20,
  },
  createChallengeCard: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
  },
  resumeButton: {
    backgroundColor: '#6366F1',
    borderColor: '#4F46E5',
    marginBottom: 25,
    marginTop: 10,
  },
  pendingChallengesIndicator: {
    backgroundColor: '#F59E0B',
    borderColor: '#D97706',
    borderWidth: 2,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    alignItems: 'center',
    width: '90%',
  },
  pendingChallengesText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Roboto-Bold',
  },
  viewChallengesButton: {
    backgroundColor: '#1F2937',
    borderColor: '#374151',
    borderWidth: 2,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  viewChallengesButtonText: {
    color: '#F59E0B',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
  },

  // PvP Game Styles
  gameStatusContainer: {
    backgroundColor: '#374151',
    borderColor: '#4B5563',
    borderWidth: 2,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    alignItems: 'center',
    width: '90%',
  },
  statusText: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    fontFamily: 'Roboto-Bold',
  },
  attemptsText: {
    color: '#E5E7EB',
    fontSize: 14,
    marginBottom: 5,
    fontFamily: 'Roboto-Regular',
  },
  gameInfoContainer: {
    backgroundColor: '#1F2937',
    borderColor: '#4B5563',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 20,
    alignItems: 'center',
    width: '90%',
  },
  gameInfoText: {
    color: '#9CA3AF',
    fontSize: 14,
    marginBottom: 5,
    fontFamily: 'Roboto-Regular',
  },
  inputContainer: {
    width: '90%',
    marginBottom: 20,
    alignItems: 'center',
  },
  inputLabel: {
    color: '#E5E7EB',
    fontSize: 16,
    marginBottom: 10,
    fontFamily: 'Roboto-Regular',
  },
  textInput: {
    backgroundColor: '#374151',
    borderColor: '#4B5563',
    borderWidth: 2,
    borderRadius: 8,
    padding: 12,
    width: '100%',
    color: '#E5E7EB',
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
    marginBottom: 15,
  },
  historyContainer: {
    width: '90%',
    marginBottom: 20,
  },
  historyTitle: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  historyEntry: {
    backgroundColor: '#374151',
    borderColor: '#4B5563',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyPlayer: {
    color: '#E5E7EB',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
    flex: 1,
  },
  historyGuess: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
    flex: 1,
    textAlign: 'center',
  },
  historyFeedback: {
    color: '#9CA3AF',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
    flex: 1,
    textAlign: 'right',
  },
  gameOverContainer: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
    borderWidth: 2,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    alignItems: 'center',
    width: '90%',
  },
  gameOverText: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 15,
    fontFamily: 'Roboto-Bold',
  },
  activeGameIndicator: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
    borderWidth: 2,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    alignItems: 'center',
    width: '90%',
  },
  activeGameText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Roboto-Bold',
  },
  // Group styling for FriendsScreen
  groupContainer: {
    width: '100%',
    marginBottom: 20,
  },
  groupTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 15,
    fontFamily: 'Roboto-Medium',
    textAlign: 'left',
  },
  // Tab styling for Friends Management
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
    marginHorizontal: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
  },
  activeTabButton: {
    backgroundColor: '#F59E0B',
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    fontFamily: 'Roboto-Medium',
  },
  activeTabButtonText: {
    color: '#1F2937',
  },
  // Missing styles for FriendsScreen and AddFriendsScreen
  searchSection: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
    backgroundColor: '#374151',
    marginBottom: 10,
    borderRadius: 12,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 10,
    width: '100%',
  },
  searchInput: {
    flex: 1,
    minWidth: 200,
    backgroundColor: '#1F2937',
    borderRadius: 8,
    padding: 12,
    color: '#E5E7EB',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#4B5563',
    fontFamily: 'Roboto-Regular',
  },
  searchButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchButtonText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
  },
  searchResults: {
    marginTop: 15,
  },
  searchResultItem: {
    backgroundColor: '#1F2937',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#4B5563',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchResultInfo: {
    flex: 1,
    marginRight: 12,
  },
  searchResultUsername: {
    fontSize: 18,
    fontWeight: '700',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 4,
  },
  friendshipStatus: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Roboto-Medium',
    marginTop: 2,
  },
  searchResultEmail: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  resultsTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 15,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Medium',
    textAlign: 'center',
  },
  userItem: {
    backgroundColor: '#1F2937',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  userInfo: {
    marginBottom: 10,
  },
  username: {
    fontSize: 18,
    fontWeight: '600',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 5,
  },
  userEmail: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  addButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#10B981',
    backgroundColor: '#10B981',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    minWidth: 80,
    alignItems: 'center',
  },
  requestItem: {
    backgroundColor: '#1F2937',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  requestInfo: {
    marginBottom: 10,
  },
  requestUsername: {
    fontSize: 18,
    fontWeight: '600',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 5,
  },
  requestText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  requestActions: {
    flexDirection: 'column',
    gap: 10,
  },
  acceptButton: {
    backgroundColor: '#10B981',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#34D399',
    borderLeftColor: '#34D399',
    borderBottomColor: '#059669',
    borderRightColor: '#059669',
  },
  declineButton: {
    backgroundColor: '#6B7280',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopColor: '#9CA3AF',
    borderLeftColor: '#9CA3AF',
    borderBottomColor: '#4B5563',
    borderRightColor: '#4B5563',
  },
  requestsContainer: {
    flex: 1,
    width: '100%',
  },
  emptyContainer: {
    alignItems: 'center',
    padding: 20,
    marginTop: 20,
  },
  emptyText: {
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 16,
    fontStyle: 'italic',
    marginTop: 20,
    fontFamily: 'Roboto-Regular',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#6B7280',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    marginTop: 5,
  },
  // Challenge text styling for better readability
  challengeUsername: {
    fontSize: 16,
    fontWeight: '600',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 3,
  },
  challengeEmail: {
    fontSize: 14,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    marginBottom: 3,
  },
  challengeDifficulty: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    fontStyle: 'italic',
    marginTop: 3,
  },
  // Challenge item container styling
  challengeItem: {
    backgroundColor: '#1F2937',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  challengeInfo: {
    marginBottom: 10,
  },
  challengeActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  
  // Tab styling for Leaderboard
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 2,
    minWidth: 0, // Allow flex to shrink
  },
  activeTab: {
    backgroundColor: '#F59E0B',
  },
  tabText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '600',
  },
  activeTabText: {
    color: '#1F2937',
  },
  
  // Difficulty tab styling for Leaderboard
  difficultyTabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginBottom: 20,
    gap: 8,
  },
  difficultyTab: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#374151',
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  activeDifficultyTab: {
    backgroundColor: '#F59E0B',
    borderColor: '#F59E0B',
  },
  difficultyTabText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  activeDifficultyTabText: {
    color: '#000000',
    fontWeight: '700',
    fontSize: 12,
    textAlign: 'center',
  },

  // Resume Games Screen
  sectionContainer: {
    marginBottom: 20,
    width: '100%',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 12,
    paddingHorizontal: 16,
  },

  // Hard Mode Unlock Styles
  hardModeUnlockContainer: {
    backgroundColor: '#1F2937',
    padding: 20,
    borderRadius: 12,
    marginHorizontal: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  unlockedContainer: {
    alignItems: 'center',
    padding: 15,
  },
  unlockedTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#10B981',
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  unlockedSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  lockedContainer: {
    padding: 15,
  },
  lockedTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#EF4444',
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  lockedSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    marginBottom: 15,
    fontFamily: 'Roboto-Regular',
  },
  unlockOptions: {
    gap: 15,
  },
  unlockOption: {
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  unlockOptionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F59E0B',
    marginBottom: 5,
    fontFamily: 'Roboto-Bold',
  },
  unlockOptionSubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 10,
    fontFamily: 'Roboto-Regular',
  },
  progressContainer: {
    backgroundColor: '#1F2937',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  progressText: {
    fontSize: 12,
    color: '#E5E7EB',
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  premiumButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  premiumButtonText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
  },

  // Locked button styles for GameScreen
  lockedButton: {
    backgroundColor: '#6B7280',
    opacity: 0.8, // Increased opacity since button is now clickable
  },
  lockedButtonText: {
    color: '#9CA3AF',
  },

  // Lock status message styles for SetWordGameScreen
  lockStatusContainer: {
    backgroundColor: '#1F2937',
    padding: 15,
    borderRadius: 8,
    marginTop: 15,
    borderWidth: 1,
    borderColor: '#4B5563',
    alignItems: 'center',
  },
  lockStatusText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#EF4444',
    textAlign: 'center',
    marginBottom: 5,
    fontFamily: 'Roboto-Medium',
  },
  lockStatusSubtext: {
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },



  // ProfileScreen difficulty section styling
  difficultySection: {
    marginBottom: 20,
    padding: 12,
    backgroundColor: '#4B5563',
    borderRadius: 8,
  },
  difficultyStatsContainer: {
    marginBottom: 20,
    padding: 12,
    backgroundColor: '#4B5563',
    borderRadius: 8,
  },
  difficultyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },

  // Notification Badge Styles
  notificationBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FF4444',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    zIndex: 1,
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },

  // Standardized Game Container Style (based on solo game design)
  standardGameItem: {
    backgroundColor: '#1F2937',
    borderRadius: 12,
    marginBottom: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#374151',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    transform: [{ scale: 1 }],
    // Add a subtle gradient effect using border
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },

  // Standardized Game Content Styles
  standardGameContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  standardGameInfo: {
    flex: 1,
    marginRight: 16,
  },
  standardGameTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 4,
  },
  standardGameSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },

  // Outgoing Challenge Container (gold border on right)
  outgoingChallengeItem: {
    backgroundColor: '#1F2937',
    borderRadius: 12,
    marginBottom: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#374151',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    transform: [{ scale: 1 }],
    // Gold border on the right side
    borderRightWidth: 4,
    borderRightColor: '#F59E0B',
  },

  // Incoming Challenge Specific Styles
  incomingChallengeContent: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 120,
  },
  incomingChallengeInfo: {
    width: '100%',
    marginBottom: 12,
    alignItems: 'center',
  },
  incomingChallengeDate: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginTop: 8,
    textAlign: 'center',
  },

  // Compact Challenge Box Styles for ResumeGamesScreen (legacy)
  compactChallengeItem: {
    flexDirection: 'row',
    backgroundColor: '#374151',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#4B5563',
    // Add gold left border effect like soloGameItem
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  compactChallengeInfo: {
    flex: 1,
    marginRight: 12,
  },
  compactChallengeTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 2,
  },
  compactChallengeUsername: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
    marginBottom: 2,
  },
  compactChallengeSubtext: {
    fontSize: 13,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    marginBottom: 1,
  },
  compactChallengeDate: {
    fontSize: 12,
    color: '#6B7280',
    fontFamily: 'Roboto-Regular',
  },
  compactChallengeButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    minWidth: 70,
    alignItems: 'center',
  },
  compactChallengeButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
  },
  
  // Solo Game Resume Styles
  soloGameItem: {
    backgroundColor: '#1F2937',
    borderRadius: 12,
    marginBottom: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#374151',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    transform: [{ scale: 1 }],
    // Add a subtle gradient effect using border
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  soloGameContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  soloGameInfo: {
    flex: 1,
    marginRight: 16,
  },
  soloGameTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 4,
  },
  soloGameSubtitle: {
    fontSize: 14,
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
    marginBottom: 2,
  },
  soloGameTime: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  soloGameAction: {
    backgroundColor: '#F59E0B',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  soloGameResumeText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Roboto-Bold',
  },

  // Enhanced styles for awaiting acceptance boxes
  awaitingAcceptanceItem: {
    flexDirection: 'row',
    backgroundColor: '#1F2937',
    padding: 14,
    borderRadius: 12,
    marginBottom: 10,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderColor: '#374151',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    // Add gold right border effect for "Waiting for username" containers
    borderRightWidth: 4,
    borderRightColor: '#F59E0B',
  },
  awaitingAcceptanceTextContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 12,
  },
  awaitingAcceptanceInfo: {
    flex: 1,
    marginRight: 12,
    alignItems: 'flex-start',
  },
  awaitingAcceptanceTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#F59E0B',
    fontFamily: 'Roboto-Bold',
    marginBottom: 2,
    textAlign: 'left',
  },
  awaitingAcceptanceUsername: {
    fontSize: 17,
    fontWeight: '700',
    fontFamily: 'Roboto-Bold',
    marginBottom: 2,
    textAlign: 'left',
  },
  awaitingAcceptanceSubtext: {
    fontSize: 14,
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
    marginBottom: 2,
    textAlign: 'left',
  },
  awaitingAcceptanceDate: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    marginTop: 8,
  },

  // Video styles
  videoButton: {
    backgroundColor: '#8B5CF6',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 20,
    alignItems: 'center',
  },
  videoButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  videoModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoContainer: {
    width: '95%',
    height: '80%',
    position: 'relative',
  },
  video: {
    flex: 1,
    borderRadius: 12,
  },
  videoCloseButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  videoCloseButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },

  settingButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginVertical: 8,
    alignItems: 'center',
  },

  settingButtonText: {
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    fontWeight: '500',
  },

  // Share Button Styles
  shareSection: {
    marginTop: 20,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  shareButton: {
    backgroundColor: '#8B5CF6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  shareButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  // CreateChallengeScreen specific back button styles
  createChallengeBackButton: {
    padding: 10,
  },
  createChallengeBackButtonText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
  },
  // Username-only purple style for inline Text
  usernamePurple: {
    color: '#8B5CF6',
  },
  
  // Unified date style for all containers
  unifiedDate: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'Roboto-Regular',
  },
  
  // Red quit button for waiting for containers
  redQuitButton: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    minWidth: 70,
    alignItems: 'center',
  },
  redQuitButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },

  // Notification Permission Popup Styles
  notificationPermissionPopup: {
    backgroundColor: '#374151',
    padding: rs(32, 40),
    borderRadius: rs(16, 20),
    alignItems: 'center',
    width: isTablet() ? '65%' : '90%',
    maxWidth: rw(400, 600),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  notificationPermissionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#F59E0B',
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: 'Roboto-Bold',
  },
  notificationPermissionMessage: {
    fontSize: 16,
    color: '#E5E7EB',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
    fontFamily: 'Roboto-Regular',
  },
  notificationPermissionBenefits: {
    backgroundColor: '#1F2937',
    padding: 20,
    borderRadius: 12,
    width: '100%',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  notificationPermissionBenefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  notificationPermissionBenefitDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F59E0B',
    marginRight: 12,
  },
  notificationPermissionBenefitText: {
    fontSize: 14,
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
    flex: 1,
  },
  notificationPermissionActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 12,
  },
  notificationPermissionButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
  },
  notificationPermissionButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#6B7280',
  },
  notificationPermissionButtonPrimary: {
    backgroundColor: '#F59E0B',
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  notificationPermissionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
  },
  notificationPermissionButtonTextSecondary: {
    color: '#9CA3AF',
  },
  notificationPermissionButtonTextPrimary: {
    color: '#1F2937',
  },
  challengeButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 12,
    gap: 8,
  },
  declineButton: {
    backgroundColor: '#DC2626',
    flex: 1,
    minWidth: 80,
    borderTopColor: '#EF4444',
    borderLeftColor: '#EF4444',
    borderBottomColor: '#B91C1C',
    borderRightColor: '#B91C1C',
  },
  acceptButton: {
    backgroundColor: '#059669',
    flex: 1,
    minWidth: 80,
    borderTopColor: '#10B981',
    borderLeftColor: '#10B981',
    borderBottomColor: '#047857',
    borderRightColor: '#047857',
  },
  backButton: {
    padding: 10,
  },
  backButtonText: {
    color: '#F59E0B',
    fontSize: 16,
    fontWeight: '600',
  },
});