import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#1F2937',
    alignItems: 'center',
    padding: 20,
    paddingHorizontal: 16,
  },
  difficultyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 20,
  },
  waitingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    padding: 20,
  },
  imageHeader: {
    width: '80%',
    maxWidth: 360,
    height: 90,
    marginTop: 80,
    marginBottom: 40,
  },
  header: {
    fontSize: 26,
    fontWeight: '600',
    marginBottom: 20,
    marginTop: 30,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    width: '100%',
  },
  soloheader: {
    fontSize: 26,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: 5,
    marginBottom: 10,
    marginTop: 10,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  button: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 8,
    width: 200,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonText: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  disabledButton: {
    backgroundColor: '#6B7280',
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 12,
    textAlign: 'center',
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  savedGameButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 8,
    marginHorizontal: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  savedGameText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  scroll: {
    width: '100%',
    paddingBottom: 50,
  },
  inputDisplay: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  inputLetter: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    textAlign: 'center',
    fontSize: 26,
    marginHorizontal: 6,
    lineHeight: 44,
    borderRadius: 6,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  filledLetter: {
    backgroundColor: '#374151',
  },
  emptyLetter: {
    backgroundColor: '#4B5563',
  },
  alphabetContainer: {
    marginBottom: 10,
    width: '100%',
    alignItems: 'center',
  },
  alphabetGrid: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 'auto',
    maxWidth: 360,
    marginHorizontal: 'auto',
    paddingBottom: 1,
    paddingHorizontal: 1,
  },
  letter: {
    width: 26,
    height: 34,
    textAlign: 'center',
    fontSize: 22,
    margin: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    lineHeight: 34,
    backgroundColor: '#374151',
    borderRadius: 5,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  eliminatedLetter: {
    backgroundColor: '#6B7280',
    color: '#E5E7EB',
  },
  presentLetter: {
    backgroundColor: '#10B981',
    color: '#1F2937',
  },
  inputControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 20,
  },
  backspaceButtonContainer: {
    backgroundColor: '#7C3AED',
    paddingVertical: 12,
    paddingHorizontal: 26,
    borderRadius: 8,
    marginHorizontal: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  guessButtonContainer: {
    backgroundColor: '#10B981',
    paddingVertical: 12,
    paddingHorizontal: 26,
    borderRadius: 8,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonTextBackspace: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  feedbackGuide: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  feedbackItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
  },
  feedbackCircle: {
    width: 15,
    height: 15,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#7C3AED',
    backgroundColor: 'transparent',
    marginRight: 6,
  },
  feedbackDot: {
    width: 15,
    height: 15,
    borderRadius: 6,
    backgroundColor: '#10B981',
    marginRight: 6,
  },
  feedbackText: {
    fontSize: 14,
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  guessRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
    marginVertical: 2,
  },
  guessWord: {
    flexDirection: 'row',
  },
  guessLetter: {
    fontSize: 26,
    marginHorizontal: 3,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  feedbackContainer: {
    flexDirection: 'row',
  },
  fabTop: {
    position: 'absolute',
    top: 30,
    right: 20,
    backgroundColor: '#F59E0B',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  fabText: {
    color: '#1F2937',
    fontSize: 26,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  modalShadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    marginVertical: 12,
    width: '100%',
    borderRadius: 8,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  invalidGuessTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  invalidGuessButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  congratsPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  congratsTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  congratsMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  congratsButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  winPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  winTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  winMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  winButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  losePopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  loseTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  loseMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  loseButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  opponentGuessesPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  opponentGuessesTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  opponentGuessesMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  opponentGuessesButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  opponentSolvedPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  opponentSolvedTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  opponentSolvedMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  maxGuessesTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  maxGuessesButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  menuPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  menuTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  menuButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  quitConfirmPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  quitConfirmTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  quitConfirmMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  quitConfirmButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  wordRevealPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  wordRevealTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  wordRevealMessage: {
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  wordRevealButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  hintPopup: {
    backgroundColor: '#374151',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '85%',
  },
  hintTitle: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
  },
  hintMessage: {
    fontSize: 16,
    textAlign: 'center',
    color: '#D1D5DB',
    fontFamily: 'Roboto-Regular',
  },
  hintButtonContainer: {
    backgroundColor: '#F59E0B',
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  hintLinkContainer: {
    marginTop: 1,
    padding: 1,
  },
  hintLink: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: '600',
    paddingTop: 1,
    paddingBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#E5E7EB',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  tutorialText: {
    color: '#D1D5DB',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  friendItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 8,
    width: '100%',
  },
  friendText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
    flex: 1,
    marginRight: 10,
  },
  // New styles for friend system
  searchSection: {
    width: '100%',
    marginBottom: 20,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    width: '100%',
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#4B5563',
    backgroundColor: '#374151',
    padding: 12,
    borderRadius: 8,
    color: '#E5E7EB',
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    marginRight: 8,
  },
  searchButton: {
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 10,
    color: '#E5E7EB',
    fontFamily: 'Roboto-Regular',
    width: '100%',
    textAlign: 'left',
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 4,
    width: '100%',
    overflow: 'hidden',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
    position: 'relative',
  },
  activeTabButton: {
    backgroundColor: '#F59E0B',
  },
  tabButtonText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  activeTabButtonText: {
    color: '#1F2937',
  },
  badge: {
    position: 'absolute',
    top: 4,
    right: 8,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
  tabContent: {
    width: '100%',
    paddingHorizontal: 4,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    width: '100%',
    justifyContent: 'space-between',
  },
  friendText: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
  },
  friendSubtext: {
    color: '#9CA3AF',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
    marginTop: 2,
  },
  emptyText: {
    color: '#9CA3AF',
    fontSize: 16,
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: 'Roboto-Regular',
    marginTop: 20,
  },
  modalText: {
    color: '#E5E7EB',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Roboto-Regular',
  },
  wordLengthContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 20,
  },
  wordLengthButton: {
    backgroundColor: '#10B981',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    margin: 4,
    minWidth: 80,
    alignItems: 'center',
  },
  wordLengthButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto-Regular',
  },
});